// js/content.js

const pageContents = {
    "Overview": `
            <section>
                <h1 class="ArticleTitle sketchy-underline">Overview Title</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            </section>
    `,

    "Example-1": `
        <section>
            <h1 class="ArticleTitle">Example-1 Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            <p>Fusce venenatis blandit viverra. Praesent accumsan odio ut nibh consectetur hendrerit. Nullam finibus, nibh sit amet scelerisque convallis, ipsum turpis sollicitudin orci, vitae porta mauris risus a libero. Quisque tincidunt mollis leo at sollicitudin. Nunc sollicitudin pharetra felis, in placerat nibh euismod eu. Sed et venenatis magna. Vestibulum at euismod felis, et euismod erat. Vestibulum aliquam mi vitae elit sagittis rutrum. Pellentesque suscipit purus non tincidunt ullamcorper. Nunc ut leo sed sapien sagittis fringilla vel sed sem.</p>
            <p>Cras tempor nisi libero, eget tincidunt nulla euismod eu. Donec sodales vitae diam ut eleifend. Donec augue eros, commodo nec quam nec, tempor euismod magna. Nam dapibus, urna sed tincidunt ultrices, arcu nunc euismod justo, at tincidunt massa augue sit amet tortor. Nam aliquam arcu non tellus imperdiet, ac fringilla libero pulvinar. Suspendisse ipsum sem, accumsan eget tempus quis, ornare sit amet nulla. Donec lacinia, felis eu tempus molestie, ante massa posuere libero, id pretium augue lorem pellentesque justo.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim neque non semper efficitur. Fusce vel neque ultrices, varius felis non, dapibus nulla. Nulla facilisi. Fusce tempus arcu ac accumsan mattis. In non congue justo. Sed in augue urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean metus libero, fringilla at ante at, euismod efficitur metus. Sed elementum, purus sit amet mollis condimentum, ipsum ante dignissim orci, vel rutrum velit mauris ac augue. Aliquam sagittis varius tellus, eget commodo orci. Nullam posuere imperdiet magna id porttitor. Ut quis ex sem.</p>
            <p>Phasellus ac nisi finibus, commodo magna non, imperdiet lorem. Quisque sed aliquet sem. Nam varius mauris a placerat hendrerit. Integer pulvinar mauris placerat odio semper, eget aliquet mi vestibulum. Suspendisse potenti. Nunc commodo vestibulum mauris. Fusce semper urna enim, et ultrices diam suscipit in. Vivamus eu gravida metus. Ut faucibus felis ipsum, vitae aliquet dui egestas ac. Suspendisse non est interdum, fringilla turpis ut, euismod ipsum. Ut id iaculis mi, eget porta purus. Vestibulum ut facilisis nunc.</p>
        </section>
    `,

    "Example-2": `
        <section>
            <h1 class="ArticleTitle">Example-2 Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            <p>Fusce venenatis blandit viverra. Praesent accumsan odio ut nibh consectetur hendrerit. Nullam finibus, nibh sit amet scelerisque convallis, ipsum turpis sollicitudin orci, vitae porta mauris risus a libero. Quisque tincidunt mollis leo at sollicitudin. Nunc sollicitudin pharetra felis, in placerat nibh euismod eu. Sed et venenatis magna. Vestibulum at euismod felis, et euismod erat. Vestibulum aliquam mi vitae elit sagittis rutrum. Pellentesque suscipit purus non tincidunt ullamcorper. Nunc ut leo sed sapien sagittis fringilla vel sed sem.</p>
            <p>Cras tempor nisi libero, eget tincidunt nulla euismod eu. Donec sodales vitae diam ut eleifend. Donec augue eros, commodo nec quam nec, tempor euismod magna. Nam dapibus, urna sed tincidunt ultrices, arcu nunc euismod justo, at tincidunt massa augue sit amet tortor. Nam aliquam arcu non tellus imperdiet, ac fringilla libero pulvinar. Suspendisse ipsum sem, accumsan eget tempus quis, ornare sit amet nulla. Donec lacinia, felis eu tempus molestie, ante massa posuere libero, id pretium augue lorem pellentesque justo.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim neque non semper efficitur. Fusce vel neque ultrices, varius felis non, dapibus nulla. Nulla facilisi. Fusce tempus arcu ac accumsan mattis. In non congue justo. Sed in augue urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean metus libero, fringilla at ante at, euismod efficitur metus. Sed elementum, purus sit amet mollis condimentum, ipsum ante dignissim orci, vel rutrum velit mauris ac augue. Aliquam sagittis varius tellus, eget commodo orci. Nullam posuere imperdiet magna id porttitor. Ut quis ex sem.</p>
            <p>Phasellus ac nisi finibus, commodo magna non, imperdiet lorem. Quisque sed aliquet sem. Nam varius mauris a placerat hendrerit. Integer pulvinar mauris placerat odio semper, eget aliquet mi vestibulum. Suspendisse potenti. Nunc commodo vestibulum mauris. Fusce semper urna enim, et ultrices diam suscipit in. Vivamus eu gravida metus. Ut faucibus felis ipsum, vitae aliquet dui egestas ac. Suspendisse non est interdum, fringilla turpis ut, euismod ipsum. Ut id iaculis mi, eget porta purus. Vestibulum ut facilisis nunc.</p>
        </section>
    `,

    "Example-Nested-2": `
        <section>
            <h1 class="ArticleTitle">Example-Nested-2 Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            <p>Fusce venenatis blandit viverra. Praesent accumsan odio ut nibh consectetur hendrerit. Nullam finibus, nibh sit amet scelerisque convallis, ipsum turpis sollicitudin orci, vitae porta mauris risus a libero. Quisque tincidunt mollis leo at sollicitudin. Nunc sollicitudin pharetra felis, in placerat nibh euismod eu. Sed et venenatis magna. Vestibulum at euismod felis, et euismod erat. Vestibulum aliquam mi vitae elit sagittis rutrum. Pellentesque suscipit purus non tincidunt ullamcorper. Nunc ut leo sed sapien sagittis fringilla vel sed sem.</p>
            <p>Cras tempor nisi libero, eget tincidunt nulla euismod eu. Donec sodales vitae diam ut eleifend. Donec augue eros, commodo nec quam nec, tempor euismod magna. Nam dapibus, urna sed tincidunt ultrices, arcu nunc euismod justo, at tincidunt massa augue sit amet tortor. Nam aliquam arcu non tellus imperdiet, ac fringilla libero pulvinar. Suspendisse ipsum sem, accumsan eget tempus quis, ornare sit amet nulla. Donec lacinia, felis eu tempus molestie, ante massa posuere libero, id pretium augue lorem pellentesque justo.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim neque non semper efficitur. Fusce vel neque ultrices, varius felis non, dapibus nulla. Nulla facilisi. Fusce tempus arcu ac accumsan mattis. In non congue justo. Sed in augue urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean metus libero, fringilla at ante at, euismod efficitur metus. Sed elementum, purus sit amet mollis condimentum, ipsum ante dignissim orci, vel rutrum velit mauris ac augue. Aliquam sagittis varius tellus, eget commodo orci. Nullam posuere imperdiet magna id porttitor. Ut quis ex sem.</p>
            <p>Phasellus ac nisi finibus, commodo magna non, imperdiet lorem. Quisque sed aliquet sem. Nam varius mauris a placerat hendrerit. Integer pulvinar mauris placerat odio semper, eget aliquet mi vestibulum. Suspendisse potenti. Nunc commodo vestibulum mauris. Fusce semper urna enim, et ultrices diam suscipit in. Vivamus eu gravida metus. Ut faucibus felis ipsum, vitae aliquet dui egestas ac. Suspendisse non est interdum, fringilla turpis ut, euismod ipsum. Ut id iaculis mi, eget porta purus. Vestibulum ut facilisis nunc.</p>
        </section>
    `,

    "Example-3": `
        <section>
            <h1 class="ArticleTitle">Example-3 Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            <p>Fusce venenatis blandit viverra. Praesent accumsan odio ut nibh consectetur hendrerit. Nullam finibus, nibh sit amet scelerisque convallis, ipsum turpis sollicitudin orci, vitae porta mauris risus a libero. Quisque tincidunt mollis leo at sollicitudin. Nunc sollicitudin pharetra felis, in placerat nibh euismod eu. Sed et venenatis magna. Vestibulum at euismod felis, et euismod erat. Vestibulum aliquam mi vitae elit sagittis rutrum. Pellentesque suscipit purus non tincidunt ullamcorper. Nunc ut leo sed sapien sagittis fringilla vel sed sem.</p>
            <p>Cras tempor nisi libero, eget tincidunt nulla euismod eu. Donec sodales vitae diam ut eleifend. Donec augue eros, commodo nec quam nec, tempor euismod magna. Nam dapibus, urna sed tincidunt ultrices, arcu nunc euismod justo, at tincidunt massa augue sit amet tortor. Nam aliquam arcu non tellus imperdiet, ac fringilla libero pulvinar. Suspendisse ipsum sem, accumsan eget tempus quis, ornare sit amet nulla. Donec lacinia, felis eu tempus molestie, ante massa posuere libero, id pretium augue lorem pellentesque justo.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim neque non semper efficitur. Fusce vel neque ultrices, varius felis non, dapibus nulla. Nulla facilisi. Fusce tempus arcu ac accumsan mattis. In non congue justo. Sed in augue urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean metus libero, fringilla at ante at, euismod efficitur metus. Sed elementum, purus sit amet mollis condimentum, ipsum ante dignissim orci, vel rutrum velit mauris ac augue. Aliquam sagittis varius tellus, eget commodo orci. Nullam posuere imperdiet magna id porttitor. Ut quis ex sem.</p>
            <p>Phasellus ac nisi finibus, commodo magna non, imperdiet lorem. Quisque sed aliquet sem. Nam varius mauris a placerat hendrerit. Integer pulvinar mauris placerat odio semper, eget aliquet mi vestibulum. Suspendisse potenti. Nunc commodo vestibulum mauris. Fusce semper urna enim, et ultrices diam suscipit in. Vivamus eu gravida metus. Ut faucibus felis ipsum, vitae aliquet dui egestas ac. Suspendisse non est interdum, fringilla turpis ut, euismod ipsum. Ut id iaculis mi, eget porta purus. Vestibulum ut facilisis nunc.</p>
        </section>
    `,

    "Example-4": `
        <section>
            <h1 class="ArticleTitle">Example-4 Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            <p>Fusce venenatis blandit viverra. Praesent accumsan odio ut nibh consectetur hendrerit. Nullam finibus, nibh sit amet scelerisque convallis, ipsum turpis sollicitudin orci, vitae porta mauris risus a libero. Quisque tincidunt mollis leo at sollicitudin. Nunc sollicitudin pharetra felis, in placerat nibh euismod eu. Sed et venenatis magna. Vestibulum at euismod felis, et euismod erat. Vestibulum aliquam mi vitae elit sagittis rutrum. Pellentesque suscipit purus non tincidunt ullamcorper. Nunc ut leo sed sapien sagittis fringilla vel sed sem.</p>
            <p>Cras tempor nisi libero, eget tincidunt nulla euismod eu. Donec sodales vitae diam ut eleifend. Donec augue eros, commodo nec quam nec, tempor euismod magna. Nam dapibus, urna sed tincidunt ultrices, arcu nunc euismod justo, at tincidunt massa augue sit amet tortor. Nam aliquam arcu non tellus imperdiet, ac fringilla libero pulvinar. Suspendisse ipsum sem, accumsan eget tempus quis, ornare sit amet nulla. Donec lacinia, felis eu tempus molestie, ante massa posuere libero, id pretium augue lorem pellentesque justo.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim neque non semper efficitur. Fusce vel neque ultrices, varius felis non, dapibus nulla. Nulla facilisi. Fusce tempus arcu ac accumsan mattis. In non congue justo. Sed in augue urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean metus libero, fringilla at ante at, euismod efficitur metus. Sed elementum, purus sit amet mollis condimentum, ipsum ante dignissim orci, vel rutrum velit mauris ac augue. Aliquam sagittis varius tellus, eget commodo orci. Nullam posuere imperdiet magna id porttitor. Ut quis ex sem.</p>
            <p>Phasellus ac nisi finibus, commodo magna non, imperdiet lorem. Quisque sed aliquet sem. Nam varius mauris a placerat hendrerit. Integer pulvinar mauris placerat odio semper, eget aliquet mi vestibulum. Suspendisse potenti. Nunc commodo vestibulum mauris. Fusce semper urna enim, et ultrices diam suscipit in. Vivamus eu gravida metus. Ut faucibus felis ipsum, vitae aliquet dui egestas ac. Suspendisse non est interdum, fringilla turpis ut, euismod ipsum. Ut id iaculis mi, eget porta purus. Vestibulum ut facilisis nunc.</p>
        </section>
    `,

    "Example-Nested-4": `
        <section>
            <h1 class="ArticleTitle">Example-Nested-4 Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            <p>Fusce venenatis blandit viverra. Praesent accumsan odio ut nibh consectetur hendrerit. Nullam finibus, nibh sit amet scelerisque convallis, ipsum turpis sollicitudin orci, vitae porta mauris risus a libero. Quisque tincidunt mollis leo at sollicitudin. Nunc sollicitudin pharetra felis, in placerat nibh euismod eu. Sed et venenatis magna. Vestibulum at euismod felis, et euismod erat. Vestibulum aliquam mi vitae elit sagittis rutrum. Pellentesque suscipit purus non tincidunt ullamcorper. Nunc ut leo sed sapien sagittis fringilla vel sed sem.</p>
            <p>Cras tempor nisi libero, eget tincidunt nulla euismod eu. Donec sodales vitae diam ut eleifend. Donec augue eros, commodo nec quam nec, tempor euismod magna. Nam dapibus, urna sed tincidunt ultrices, arcu nunc euismod justo, at tincidunt massa augue sit amet tortor. Nam aliquam arcu non tellus imperdiet, ac fringilla libero pulvinar. Suspendisse ipsum sem, accumsan eget tempus quis, ornare sit amet nulla. Donec lacinia, felis eu tempus molestie, ante massa posuere libero, id pretium augue lorem pellentesque justo.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim neque non semper efficitur. Fusce vel neque ultrices, varius felis non, dapibus nulla. Nulla facilisi. Fusce tempus arcu ac accumsan mattis. In non congue justo. Sed in augue urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean metus libero, fringilla at ante at, euismod efficitur metus. Sed elementum, purus sit amet mollis condimentum, ipsum ante dignissim orci, vel rutrum velit mauris ac augue. Aliquam sagittis varius tellus, eget commodo orci. Nullam posuere imperdiet magna id porttitor. Ut quis ex sem.</p>
            <p>Phasellus ac nisi finibus, commodo magna non, imperdiet lorem. Quisque sed aliquet sem. Nam varius mauris a placerat hendrerit. Integer pulvinar mauris placerat odio semper, eget aliquet mi vestibulum. Suspendisse potenti. Nunc commodo vestibulum mauris. Fusce semper urna enim, et ultrices diam suscipit in. Vivamus eu gravida metus. Ut faucibus felis ipsum, vitae aliquet dui egestas ac. Suspendisse non est interdum, fringilla turpis ut, euismod ipsum. Ut id iaculis mi, eget porta purus. Vestibulum ut facilisis nunc.</p>
        </section>
    `,

    "Example-5": `
        <section>
            <h1 class="ArticleTitle">Example-5 Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            <p>Fusce venenatis blandit viverra. Praesent accumsan odio ut nibh consectetur hendrerit. Nullam finibus, nibh sit amet scelerisque convallis, ipsum turpis sollicitudin orci, vitae porta mauris risus a libero. Quisque tincidunt mollis leo at sollicitudin. Nunc sollicitudin pharetra felis, in placerat nibh euismod eu. Sed et venenatis magna. Vestibulum at euismod felis, et euismod erat. Vestibulum aliquam mi vitae elit sagittis rutrum. Pellentesque suscipit purus non tincidunt ullamcorper. Nunc ut leo sed sapien sagittis fringilla vel sed sem.</p>
            <p>Cras tempor nisi libero, eget tincidunt nulla euismod eu. Donec sodales vitae diam ut eleifend. Donec augue eros, commodo nec quam nec, tempor euismod magna. Nam dapibus, urna sed tincidunt ultrices, arcu nunc euismod justo, at tincidunt massa augue sit amet tortor. Nam aliquam arcu non tellus imperdiet, ac fringilla libero pulvinar. Suspendisse ipsum sem, accumsan eget tempus quis, ornare sit amet nulla. Donec lacinia, felis eu tempus molestie, ante massa posuere libero, id pretium augue lorem pellentesque justo.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim neque non semper efficitur. Fusce vel neque ultrices, varius felis non, dapibus nulla. Nulla facilisi. Fusce tempus arcu ac accumsan mattis. In non congue justo. Sed in augue urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean metus libero, fringilla at ante at, euismod efficitur metus. Sed elementum, purus sit amet mollis condimentum, ipsum ante dignissim orci, vel rutrum velit mauris ac augue. Aliquam sagittis varius tellus, eget commodo orci. Nullam posuere imperdiet magna id porttitor. Ut quis ex sem.</p>
            <p>Phasellus ac nisi finibus, commodo magna non, imperdiet lorem. Quisque sed aliquet sem. Nam varius mauris a placerat hendrerit. Integer pulvinar mauris placerat odio semper, eget aliquet mi vestibulum. Suspendisse potenti. Nunc commodo vestibulum mauris. Fusce semper urna enim, et ultrices diam suscipit in. Vivamus eu gravida metus. Ut faucibus felis ipsum, vitae aliquet dui egestas ac. Suspendisse non est interdum, fringilla turpis ut, euismod ipsum. Ut id iaculis mi, eget porta purus. Vestibulum ut facilisis nunc.</p>
        </section>
    `,

    "Example-Nested-Title-5": `
        <section>
            <h1 class="ArticleTitle">Example-Nested-Title-5 Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            <p>Fusce venenatis blandit viverra. Praesent accumsan odio ut nibh consectetur hendrerit. Nullam finibus, nibh sit amet scelerisque convallis, ipsum turpis sollicitudin orci, vitae porta mauris risus a libero. Quisque tincidunt mollis leo at sollicitudin. Nunc sollicitudin pharetra felis, in placerat nibh euismod eu. Sed et venenatis magna. Vestibulum at euismod felis, et euismod erat. Vestibulum aliquam mi vitae elit sagittis rutrum. Pellentesque suscipit purus non tincidunt ullamcorper. Nunc ut leo sed sapien sagittis fringilla vel sed sem.</p>
            <p>Cras tempor nisi libero, eget tincidunt nulla euismod eu. Donec sodales vitae diam ut eleifend. Donec augue eros, commodo nec quam nec, tempor euismod magna. Nam dapibus, urna sed tincidunt ultrices, arcu nunc euismod justo, at tincidunt massa augue sit amet tortor. Nam aliquam arcu non tellus imperdiet, ac fringilla libero pulvinar. Suspendisse ipsum sem, accumsan eget tempus quis, ornare sit amet nulla. Donec lacinia, felis eu tempus molestie, ante massa posuere libero, id pretium augue lorem pellentesque justo.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim neque non semper efficitur. Fusce vel neque ultrices, varius felis non, dapibus nulla. Nulla facilisi. Fusce tempus arcu ac accumsan mattis. In non congue justo. Sed in augue urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean metus libero, fringilla at ante at, euismod efficitur metus. Sed elementum, purus sit amet mollis condimentum, ipsum ante dignissim orci, vel rutrum velit mauris ac augue. Aliquam sagittis varius tellus, eget commodo orci. Nullam posuere imperdiet magna id porttitor. Ut quis ex sem.</p>
            <p>Phasellus ac nisi finibus, commodo magna non, imperdiet lorem. Quisque sed aliquet sem. Nam varius mauris a placerat hendrerit. Integer pulvinar mauris placerat odio semper, eget aliquet mi vestibulum. Suspendisse potenti. Nunc commodo vestibulum mauris. Fusce semper urna enim, et ultrices diam suscipit in. Vivamus eu gravida metus. Ut faucibus felis ipsum, vitae aliquet dui egestas ac. Suspendisse non est interdum, fringilla turpis ut, euismod ipsum. Ut id iaculis mi, eget porta purus. Vestibulum ut facilisis nunc.</p>
        </section>
    `,

    "Example-Double-Nested-5": `
        <section>
            <h1 class="ArticleTitle">Example-Double-Nested-5 Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquet augue et metus dignissim porttitor. Proin et leo in ligula congue eleifend. Phasellus nec dictum dui. Suspendisse nec libero sed sem lacinia tempor sed sed mi. Nam convallis ante vel orci vestibulum sodales. Etiam pretium efficitur elit, at consectetur dolor elementum et. Proin bibendum mauris sit amet placerat luctus. In hac habitasse platea dictumst. Etiam posuere porta quam, et ornare leo sollicitudin ut. Etiam sed est ac erat fringilla consectetur. Aliquam eu tincidunt lectus, quis vestibulum ante.</p>
            <p>Fusce venenatis blandit viverra. Praesent accumsan odio ut nibh consectetur hendrerit. Nullam finibus, nibh sit amet scelerisque convallis, ipsum turpis sollicitudin orci, vitae porta mauris risus a libero. Quisque tincidunt mollis leo at sollicitudin. Nunc sollicitudin pharetra felis, in placerat nibh euismod eu. Sed et venenatis magna. Vestibulum at euismod felis, et euismod erat. Vestibulum aliquam mi vitae elit sagittis rutrum. Pellentesque suscipit purus non tincidunt ullamcorper. Nunc ut leo sed sapien sagittis fringilla vel sed sem.</p>
            <p>Cras tempor nisi libero, eget tincidunt nulla euismod eu. Donec sodales vitae diam ut eleifend. Donec augue eros, commodo nec quam nec, tempor euismod magna. Nam dapibus, urna sed tincidunt ultrices, arcu nunc euismod justo, at tincidunt massa augue sit amet tortor. Nam aliquam arcu non tellus imperdiet, ac fringilla libero pulvinar. Suspendisse ipsum sem, accumsan eget tempus quis, ornare sit amet nulla. Donec lacinia, felis eu tempus molestie, ante massa posuere libero, id pretium augue lorem pellentesque justo.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim neque non semper efficitur. Fusce vel neque ultrices, varius felis non, dapibus nulla. Nulla facilisi. Fusce tempus arcu ac accumsan mattis. In non congue justo. Sed in augue urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean metus libero, fringilla at ante at, euismod efficitur metus. Sed elementum, purus sit amet mollis condimentum, ipsum ante dignissim orci, vel rutrum velit mauris ac augue. Aliquam sagittis varius tellus, eget commodo orci. Nullam posuere imperdiet magna id porttitor. Ut quis ex sem.</p>
            <p>Phasellus ac nisi finibus, commodo magna non, imperdiet lorem. Quisque sed aliquet sem. Nam varius mauris a placerat hendrerit. Integer pulvinar mauris placerat odio semper, eget aliquet mi vestibulum. Suspendisse potenti. Nunc commodo vestibulum mauris. Fusce semper urna enim, et ultrices diam suscipit in. Vivamus eu gravida metus. Ut faucibus felis ipsum, vitae aliquet dui egestas ac. Suspendisse non est interdum, fringilla turpis ut, euismod ipsum. Ut id iaculis mi, eget porta purus. Vestibulum ut facilisis nunc.</p>
        </section>
    `,



};

window.pageContents = pageContents;   // make it globally available